version: 1.1.{build}
image: Visual Studio 2017
build_script:
- ps: "Push-Location sprintf.NET\n@(\"x86\",\"x64\",\"ARM\") | ForEach-Object { \n  msbuild -t:Restore,Build -p:Platform=$_,Configuration=Release,TargetFramework=uap10.0,Version=$env:APPVEYOR_BUILD_VERSION }\n\nmsbuild -t:Restore,Build -p:Platform=AnyCPU,Configuration=Release,TargetFramework=netstandard1.4,Version=$env:APPVEYOR_BUILD_VERSION\n\nPop-Location\nnuget pack -Version $env:APPVEYOR_BUILD_VERSION"
artifacts:
- path: '**\*.nupkg'
deploy:
- provider: NuGet
  api_key:
    secure: +7xnWj2H6CI1zQJHcbFMDRCJcSn1HYWp2HgKSRGRn5QxmrVhkdgUcddOSsLewFkm
  skip_symbols: true