name: Continuous

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
        - os: ubuntu-latest
          arch: linux-x64
        - os: windows-latest
          arch: [ win-x64, win-x86 ]

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101

    - name: Test
      run: dotnet test --configuration Release --verbosity normal --runtime ${{ matrix.arch }}
